{% set name = "pydantic" %}
{% set version = "1.10.8" %}
{% set repo_url = "https://github.com/pydantic/pydantic" %}
{% set docs_url = "https://pydantic-docs.helpmanual.io" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1410275520dfa70effadf4c21811d755e7ef9bb1f1d077a21958153a92c8d9ca

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - hatchling
   # - hatch-fancy-pypi-readme >=22.5.0
    - pip
    - setuptools
    - wheel
  run:
    - python
    - typing-extensions >=4.6.1
    - annotated-types >=0.4.0
    - pydantic-core 0.38.0
  run_constrained:
    - email-validator >=2.0.0

test:
  imports:
    - {{ name }}
  source_files:
    - tests
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest
    - pytest tests

about:
  home: {{ repo_url }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://github.com/{{ name }}/{{ name }}/blob/v{{ version }}/LICENSE
  summary: Data validation and settings management using python type hinting
  description: |
    Data validation and settings management using python type hinting.
    See documentation <{{ docs_url }}> for more details.
  doc_url: {{ docs_url }}
  doc_source_url: https://github.com/pydantic/pydantic/tree/main/docs
  dev_url: {{ repo_url }}

extra:
  recipe-maintainers:
    - samuelcolvin
    - dgasmith
