{% set name = "pydantic" %}
{% set version = "1.10.2" %}
{% set repo_url = "https://github.com/pydantic/pydantic" %}
{% set docs_url = "https://pydantic-docs.helpmanual.io" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 91b8e218852ef6007c2b98cd861601c6a09f1aa32bbbb74fab5b1c33d4a1e410

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  skip: true  # [py<=36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
    - setuptools
    - wheel
  run:
    - python
    - dataclasses >=0.6  # [py<37]
    # optional deps
    - email-validator >=1.0.3
    - typing-extensions >=4.1.0

test:
  imports:
    - {{ name }}
  requires:
    - pip
  commands:
    - pip check

about:
  home: {{ repo_url }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://github.com/{{ name }}/{{ name }}/blob/v{{ version }}/LICENSE
  summary: Data validation and settings management using python type hinting
  description: |
    Data validation and settings management using python type hinting.
    See documentation <{{ docs_url }}> for more details.
  doc_url: {{ docs_url }}
  dev_url: {{ repo_url }}

extra:
  recipe-maintainers:
    - samuelcolvin
    - dgasmith
